apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-api
spec:
  selector:
    matchLabels:
      app: modern-api
  template:
    metadata:
      labels:
        app: modern-api
    spec:
      containers:
      - name: modern-api
        image: anthonyikeda/modern-api:0.0.5
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://my-release-postgresql.default:5432/modern_db
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 130
          periodSeconds: 60


